### PR TITLE
jsPerf: Tweak Contributors wording and add link in foot.tpl. [jddalton]

### PR DESCRIPTION
**Pull request by jdalton**
Tweak Contributors wording and add link in `foot.tpl`.
Addresses issue #17.

### CODE REVIEW

**Comment by mikesherov** [comment]
link to https://github.com/mathiasbynens/jsperf.com/contributors ?

**Comment by mathiasbynens** [comment]
@mikesherov +1 I was thinking the same thing.

**Comment by mikesherov** [comment]
I meant, perhaps the contributors page should have a link to https://github.com/mathiasbynens/jsperf.com/contributors

**Comment by mikesherov** [comment]
I meant, perhaps you should also ADD a link to the contributors.

**Comment by jdalton** [comment]
Added :3

**Comment by mikesherov** [comment]
I consider this meeting of the bikeshed painting committee closed.

**Pull request merged**
