### PR TITLE
unprefix vendors CSS (not all)

### PR DESCRIPTION
**Pull request by tomByrer**
http://caniuse.com/border-radius
http://caniuse.com/css-gradients
http://caniuse.com/css3-tabsize

left in:
All -webkit- for iOS/Safari <=6.1
http://caniuse.com/css3-boxsizing (Android 3.0, Firefox v28?)

``` css
background-image: -webkit-gradient(linear, left top, left bottom, from(#ebebeb), to(#b8b8b8));
background-image: -webkit-linear-gradient(top, #ebebeb, #b8b8b8);
```

### CODE REVIEW

**Comment by tomByrer** [comment]
Not sure if you want all unprefixed & automate the prefixing.

**Comment by mathiasbynens** [comment]
jsPerf is in a unique situation where we actively support extremely old versions of current browsers. Think Firefox 2, Safari 3, etc. I agree things like `border-radius` fall under progressive enhancement, but it really doesn’t hurt to have those few extra lines of CSS there IMHO.

**Comment by tomByrer** [comment]
> we actively support extremely old versions of current browsers

Ah, I didn't realize that.  I figured you'd go back 1 year, not 4.
cheers

**Comment by mathiasbynens** [comment]
Yeah, we want people to run JavaScript performance tests in IE6 and other ancient browsers if they want to. (This patch wouldn’t change that, of course, but still I’d prefer to keep those few lines of CSS.)

**Pull request closed without merging**
